### ISSUE TITLE
오브젝트 추가하기 부분 저작권 확인 링크 오류

### ISSUE THREAD

**Issue by bpforest** [entrylabs/docs#96]
https://docs.playentry.org/user/popup_object.html#%E2%91%A1-%ED%8C%8C%EC%9D%BC-%EC%98%AC%EB%A6%AC%EA%B8%B0-%ED%83%AD
![image](https://github.com/user-attachments/assets/416880ef-2ea4-47d0-b093-dedcf499f28c)
저작권에 대해 알아보기 링크가 작동되지 않습니다.

**Comment by kimorkim** [comment]
@bpforest 제보 감사합니다.
